---
title: "Aplicaciones Shiny en documentos HTML geneados con RMarkdown"
author: "Fernando San Segundo"
date: "22/9/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

Este documeto RMarkdown genera HTML interactivo gracias a Shiny. Para aprender más  consultar:  

+ [Web oficial de Shiny (muy recomendable ver la galería de ejemplos)](https://shiny.rstudio.com)
+ [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html)

## Shiny

```{r demoNormal, echo=FALSE}
inputPanel(
    sliderInput("media",
              "Media:",
              min = -2.5,
              max = 2.5,
              step = 0.1,
              value = 0),
    sliderInput("desvTip",
              "Desviación típica:",
              min = 0.1,
              max = 2,
              step = 0.1,
              value = 1)
)

renderPlot({
  
  # generate data using the input$ variables
  data <- tibble(x = rnorm(n = 1000, 
                mean = input$media, 
                sd = input$desvTip)) %>% 
      mutate(y = dnorm(x, mean = input$media, 
                       sd = input$desvTip))
      
  # draw the normal curve
  ggplot(data) + 
      geom_point(aes(x, y)) + 
      xlim(-3, 3)
    })
```

